projects:
  demoapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: coww545sd5ayzfasih44aqhta4
      endpoints:
        prod: >-
          https://unlwq36d5fhpnmnfcnbyvh6ove.appsync-api.us-east-1.amazonaws.com/graphql
