// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "demoapp-20181207231438-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2kbx0q3krjptx.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:73b9a670-9606-4f65-ad86-1bc60e7eda56",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rjtzrY6yb",
    "aws_user_pools_web_client_id": "6lecpjfbfrj61dp4qb22e3h9fn",
    "aws_user_files_s3_bucket": "demo-app-storage",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AWSPricing",
            "endpoint": "https://52emjepgy7.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "SendEmail",
            "endpoint": "https://bgis11wqii.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://wspooc4q5zflnd65jqadswggou.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
